- hosts: wind
  tasks:
    - name: Create a directory
      win_file:
        path: C:\ansible-folder
        state: directory

    - name: Download file from online
      win_get_url:
        url: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.7.2.tar.xz
        dest: C:\ansible-folder\linux-6.7.2.tar.xz
